### PR TITLE
Get npm test working 

### PR DESCRIPTION
**Pull request by tknobi**
just wanted to run the mocha test and found this typo :)

### CODE REVIEW

**Comment by AckerApple** [comment]
reviewing now

**Comment by AckerApple** [comment]
Please confirm the typo is a case sensitivity

I would appear so but the test works on my Mac

Perhaps the fix would be to change the require statement and NOT the file name? But I am not picky

Just want to confirm the typo is a case sensitive correction and if so I am good to merge

**Comment by knoblochtobias** [comment]
Thanks for the fast answer ;)

> Please confirm the typo is a case sensitivity

Yes it is

> I would appear so but the test works on my Mac

With the typo, the test did not work on my Linux Mint.

> Perhaps the fix would be to change the require statement and NOT the file name? But I am not picky

I don't care, do it like you prefer ;)

**Comment by AckerApple** [comment]
Thank you extra kindly. I have merged. I will get to publishing to npm after I try to integrate Appveyor and Travis testing.

As seen in new issue #2

**Pull request merged**
